package com.willstep.ptutools.dataaccess.dto

enum class Type(
    val effectivityMap: Map<String, Double>,
    val displayName: String
) {
    BUG(
        mapOf("normal" to 1.0,
        "fire" to 1.5,
        "water" to 1.0,
        "electric" to 1.0,
        "grass" to 0.5,
        "ice" to 1.0,
        "fighting" to 0.5,
        "poison" to 1.0,
        "ground" to 0.5,
        "flying" to 1.5,
        "psychic" to 1.0,
        "bug" to 1.0,
        "rock" to 1.5,
        "ghost" to 1.0,
        "dragon" to 1.0,
        "dark" to 1.0,
        "steel" to 1.0,
        "fairy" to 1.0), "Bug"
    ),
    DARK(
        mapOf("normal" to 1.0,
        "fire" to 1.0,
        "water" to 1.0,
        "electric" to 1.0,
        "grass" to 1.0,
        "ice" to 1.0,
        "fighting" to 1.5,
        "poison" to 1.0,
        "ground" to 1.0,
        "flying" to 1.0,
        "psychic" to 0.0,
        "bug" to 1.5,
        "rock" to 1.0,
        "ghost" to 0.5,
        "dragon" to 1.0,
        "dark" to 0.5,
        "steel" to 1.0,
        "fairy" to 1.5), "Dark"
    ),
    DRAGON(
        mapOf("normal" to 1.0,
        "fire" to 0.5,
        "water" to 0.5,
        "electric" to 0.5,
        "grass" to 0.5,
        "ice" to 1.5,
        "fighting" to 1.0,
        "poison" to 1.0,
        "ground" to 1.0,
        "flying" to 1.0,
        "psychic" to 1.0,
        "bug" to 1.0,
        "rock" to 1.0,
        "ghost" to 1.0,
        "dragon" to 1.5,
        "dark" to 1.0,
        "steel" to 1.0,
        "fairy" to 1.5), "Dragon"
    ),
    ELECTRIC(
        mapOf("normal" to 1.0,
        "fire" to 1.0,
        "water" to 1.0,
        "electric" to 0.5,
        "grass" to 1.0,
        "ice" to 1.0,
        "fighting" to 1.0,
        "poison" to 1.0,
        "ground" to 1.5,
        "flying" to 0.5,
        "psychic" to 1.0,
        "bug" to 1.0,
        "rock" to 1.0,
        "ghost" to 1.0,
        "dragon" to 1.0,
        "dark" to 1.0,
        "steel" to 0.5,
        "fairy" to 1.0), "Electric"
    ),
    FAIRY(
        mapOf("normal" to 1.0,
        "fire" to 1.0,
        "water" to 1.0,
        "electric" to 1.0,
        "grass" to 1.0,
        "ice" to 1.0,
        "fighting" to 0.5,
        "poison" to 1.5,
        "ground" to 1.0,
        "flying" to 1.0,
        "psychic" to 1.0,
        "bug" to 0.5,
        "rock" to 1.0,
        "ghost" to 1.0,
        "dragon" to 0.0,
        "dark" to 0.5,
        "steel" to 1.5,
        "fairy" to 1.0), "Fairy"
    ),
    FIGHTING(
        mapOf("normal" to 1.0,
        "fire" to 1.0,
        "water" to 1.0,
        "electric" to 1.0,
        "grass" to 1.0,
        "ice" to 1.0,
        "fighting" to 1.0,
        "poison" to 1.0,
        "ground" to 1.0,
        "flying" to 1.5,
        "psychic" to 1.5,
        "bug" to 0.5,
        "rock" to 0.5,
        "ghost" to 1.0,
        "dragon" to 1.0,
        "dark" to 0.5,
        "steel" to 1.0,
        "fairy" to 1.5), "Fighting"
    ),
    FIRE(
        mapOf("normal" to 1.0,
        "fire" to 0.5,
        "water" to 1.5,
        "electric" to 1.0,
        "grass" to 0.5,
        "ice" to 0.5,
        "fighting" to 1.0,
        "poison" to 1.0,
        "ground" to 1.5,
        "flying" to 1.0,
        "psychic" to 1.0,
        "bug" to 0.5,
        "rock" to 1.5,
        "ghost" to 1.0,
        "dragon" to 1.0,
        "dark" to 1.0,
        "steel" to 0.5,
        "fairy" to 0.5), "Fire"
    ),
    FLYING(
        mapOf("normal" to 1.0,
        "fire" to 1.0,
        "water" to 1.0,
        "electric" to 1.5,
        "grass" to 0.5,
        "ice" to 1.5,
        "fighting" to 0.5,
        "poison" to 1.0,
        "ground" to 1.0,
        "flying" to 1.0,
        "psychic" to 1.0,
        "bug" to 0.5,
        "rock" to 1.5,
        "ghost" to 1.0,
        "dragon" to 1.0,
        "dark" to 1.0,
        "steel" to 1.0,
        "fairy" to 1.0), "Flying"
    ),
    GHOST(
        mapOf("normal" to 0.0,
        "fire" to 1.0,
        "water" to 1.0,
        "electric" to 1.0,
        "grass" to 1.0,
        "ice" to 1.0,
        "fighting" to 0.0,
        "poison" to 0.5,
        "ground" to 1.0,
        "flying" to 1.0,
        "psychic" to 1.0,
        "bug" to 0.5,
        "rock" to 1.0,
        "ghost" to 1.5,
        "dragon" to 1.0,
        "dark" to 1.5,
        "steel" to 1.0,
        "fairy" to 1.0), "Ghost"
    ),
    GRASS(
        mapOf("normal" to 1.0,
        "fire" to 1.5,
        "water" to 0.5,
        "electric" to 0.5,
        "grass" to 0.5,
        "ice" to 1.5,
        "fighting" to 1.0,
        "poison" to 1.5,
        "ground" to 0.5,
        "flying" to 1.5,
        "psychic" to 1.0,
        "bug" to 1.5,
        "rock" to 1.0,
        "ghost" to 1.0,
        "dragon" to 1.0,
        "dark" to 1.0,
        "steel" to 1.0,
        "fairy" to 1.0), "Grass"
    ),
    GROUND(
        mapOf("normal" to 1.0,
        "fire" to 1.0,
        "water" to 1.5,
        "electric" to 0.0,
        "grass" to 1.5,
        "ice" to 1.5,
        "fighting" to 1.0,
        "poison" to 0.5,
        "ground" to 1.0,
        "flying" to 1.0,
        "psychic" to 1.0,
        "bug" to 1.0,
        "rock" to 0.5,
        "ghost" to 1.0,
        "dragon" to 1.0,
        "dark" to 1.0,
        "steel" to 1.0,
        "fairy" to 1.0), "Ground"
    ),
    ICE(
        mapOf("normal" to 1.0,
        "fire" to 1.5,
        "water" to 1.0,
        "electric" to 1.0,
        "grass" to 1.0,
        "ice" to 0.5,
        "fighting" to 1.5,
        "poison" to 1.0,
        "ground" to 1.0,
        "flying" to 1.0,
        "psychic" to 1.0,
        "bug" to 1.0,
        "rock" to 1.5,
        "ghost" to 1.0,
        "dragon" to 1.0,
        "dark" to 1.0,
        "steel" to 1.5,
        "fairy" to 1.0), "Ice"
    ),
    NORMAL(
        mapOf("normal" to 1.0,
        "fire" to 1.0,
        "water" to 1.0,
        "electric" to 1.0,
        "grass" to 1.0,
        "ice" to 1.0,
        "fighting" to 1.5,
        "poison" to 1.0,
        "ground" to 1.0,
        "flying" to 1.0,
        "psychic" to 1.0,
        "bug" to 1.0,
        "rock" to 1.0,
        "ghost" to 0.0,
        "dragon" to 1.0,
        "dark" to 1.0,
        "steel" to 1.0,
        "fairy" to 1.0), "Normal"
    ),
    POISON(
        mapOf("normal" to 1.0,
        "fire" to 1.0,
        "water" to 1.0,
        "electric" to 1.0,
        "grass" to 0.5,
        "ice" to 1.0,
        "fighting" to 0.5,
        "poison" to 0.5,
        "ground" to 1.5,
        "flying" to 1.0,
        "psychic" to 1.5,
        "bug" to 0.5,
        "rock" to 1.0,
        "ghost" to 1.0,
        "dragon" to 1.0,
        "dark" to 1.0,
        "steel" to 1.0,
        "fairy" to 0.5), "Poison"
    ),
    PSYCHIC(
        mapOf("normal" to 1.0,
        "fire" to 1.0,
        "water" to 1.0,
        "electric" to 1.0,
        "grass" to 1.0,
        "ice" to 1.0,
        "fighting" to 0.5,
        "poison" to 1.0,
        "ground" to 1.0,
        "flying" to 1.0,
        "psychic" to 0.5,
        "bug" to 1.5,
        "rock" to 1.0,
        "ghost" to 1.5,
        "dragon" to 1.0,
        "dark" to 1.5,
        "steel" to 1.0,
        "fairy" to 1.0), "Psychic"
    ),
    ROCK(
        mapOf("normal" to 0.5,
        "fire" to 0.5,
        "water" to 1.5,
        "electric" to 1.0,
        "grass" to 1.5,
        "ice" to 1.0,
        "fighting" to 1.5,
        "poison" to 0.5,
        "ground" to 1.5,
        "flying" to 0.5,
        "psychic" to 1.0,
        "bug" to 1.0,
        "rock" to 1.0,
        "ghost" to 1.0,
        "dragon" to 1.0,
        "dark" to 1.0,
        "steel" to 1.5,
        "fairy" to 1.0), "Rock"
    ),
    STEEL(
        mapOf("normal" to 0.5,
        "fire" to 1.5,
        "water" to 1.0,
        "electric" to 1.0,
        "grass" to 0.5,
        "ice" to 0.5,
        "fighting" to 1.5,
        "poison" to 0.0,
        "ground" to 1.5,
        "flying" to 0.5,
        "psychic" to 0.5,
        "bug" to 0.5,
        "rock" to 0.5,
        "ghost" to 1.0,
        "dragon" to 0.5,
        "dark" to 1.0,
        "steel" to 0.5,
        "fairy" to 0.5), "Steel"
    ),
    WATER(
        mapOf("normal" to 1.0,
        "fire" to 0.5,
        "water" to 0.5,
        "electric" to 1.5,
        "grass" to 1.5,
        "ice" to 0.5,
        "fighting" to 1.0,
        "poison" to 1.0,
        "ground" to 1.0,
        "flying" to 1.0,
        "psychic" to 1.0,
        "bug" to 1.0,
        "rock" to 1.0,
        "ghost" to 1.0,
        "dragon" to 1.0,
        "dark" to 1.0,
        "steel" to 0.5,
        "fairy" to 1.0), "Water"
    )
}