global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pokesheets:8080']